ARCH=arm
CROSS_COMPILE=/home/maciej/Desktop/moje/programming/Linux/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-

ioctl_test: ioctl_test.c
	$(CROSS_COMPILE)gcc -o $@ $^


clean:
	rm ioctl_test



